// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASqPQ6_XRkSL8Ca1EJdJ7w1z64sDclzJU',
    appId: '1:876944865345:web:b45f58d98855c363592ec0',
    messagingSenderId: '876944865345',
    projectId: 'second-mart-c5c09',
    authDomain: 'second-mart-c5c09.firebaseapp.com',
    storageBucket: 'second-mart-c5c09.firebasestorage.app',
    measurementId: 'G-3QX3RYD4B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_y-2YiyRM9WVE3gJ_HRCLCzm7uAvZ22c',
    appId: '1:876944865345:android:caa84b892db05e14592ec0',
    messagingSenderId: '876944865345',
    projectId: 'second-mart-c5c09',
    storageBucket: 'second-mart-c5c09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqCgz_gLmY4uNWlCBXzVvnxc8iHWmiMps',
    appId: '1:876944865345:ios:1dfa6bdf4de0d1dc592ec0',
    messagingSenderId: '876944865345',
    projectId: 'second-mart-c5c09',
    storageBucket: 'second-mart-c5c09.firebasestorage.app',
    iosBundleId: 'com.example.secondMart',
  );
}
